# Generated by Django 4.2.1 on 2023-05-24 18:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_propiedad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('metros_cubiertos', models.IntegerField(blank=True, null=True)),
                ('metros_terreno', models.IntegerField(blank=True, null=True)),
                ('baños', models.IntegerField(blank=True, null=True)),
                ('cochera', models.IntegerField(blank=True, null=True)),
                ('dormitorios', models.IntegerField(blank=True, null=True)),
                ('amueblado', models.BooleanField(default=False)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='ventas_imagenes/')),
                ('disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inmuebles.estado')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inmuebles.localidad')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inmuebles.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('metros_cubiertos', models.IntegerField(blank=True, null=True)),
                ('metros_terreno', models.IntegerField(blank=True, null=True)),
                ('baños', models.IntegerField(blank=True, null=True)),
                ('cochera', models.IntegerField(blank=True, null=True)),
                ('dormitorios', models.IntegerField(blank=True, null=True)),
                ('amueblado', models.BooleanField(default=False)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='alquiler_imagenes/')),
                ('disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inmuebles.estado')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inmuebles.localidad')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inmuebles.tipo')),
            ],
        ),
    ]
