# Generated by Django 4.2.1 on 2023-05-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ventas_imagenes/'),
        ),
    ]
