# Generated by Django 4.2.1 on 2023-05-24 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0003_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='tipo_moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inmuebles.moneda'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='tipo_moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inmuebles.moneda'),
        ),
    ]
