# Generated by Django 3.2.19 on 2023-05-26 22:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0004_alquiler_tipo_moneda_ventas_tipo_moneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baños',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dormitorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('amueblado', models.BooleanField(default=False)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Metros_cubiertos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('metros', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='Metros_terreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('metros', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inmuebles.moneda')),
                ('precio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Serv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Venta, Alquiler, Venta y Alquiler', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='disponibilidad',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='tipo_moneda',
        ),
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(help_text='Disponible?, Vendido?', max_length=50),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='tipo_propiedad',
            field=models.CharField(help_text='Casa, Depto, etc', max_length=200),
        ),
        migrations.DeleteModel(
            name='Alquiler',
        ),
        migrations.DeleteModel(
            name='Ventas',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='disponibilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inmuebles.estado'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inmuebles.localidad'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inmuebles.tipo'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='tipo_serv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inmuebles.tipo_serv'),
        ),
        migrations.AddField(
            model_name='garage',
            name='garage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.inmueble'),
        ),
        migrations.AddField(
            model_name='dormitorio',
            name='dormitorio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.inmueble'),
        ),
        migrations.AddField(
            model_name='baños',
            name='baños',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.inmueble'),
        ),
    ]
