# Generated by Django 3.2.19 on 2023-05-26 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0005_auto_20230526_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Características',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metros_cubiertos', models.IntegerField(blank=True, null=True)),
                ('metros_terreno', models.IntegerField(blank=True, null=True)),
                ('baños', models.IntegerField(blank=True, null=True)),
                ('garage', models.IntegerField(blank=True, null=True)),
                ('dormitorio', models.IntegerField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('moneda', models.IntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
        ),
        migrations.RemoveField(
            model_name='baños',
            name='baños',
        ),
        migrations.RemoveField(
            model_name='dormitorio',
            name='dormitorio',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='garage',
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.RemoveField(
            model_name='metros_cubiertos',
            name='metros',
        ),
        migrations.RemoveField(
            model_name='metros_terreno',
            name='metros',
        ),
        migrations.RemoveField(
            model_name='precio',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='precio',
            name='precio',
        ),
        migrations.DeleteModel(
            name='Baños',
        ),
        migrations.DeleteModel(
            name='Dormitorio',
        ),
        migrations.DeleteModel(
            name='Garage',
        ),
        migrations.DeleteModel(
            name='Metros_cubiertos',
        ),
        migrations.DeleteModel(
            name='Metros_terreno',
        ),
        migrations.DeleteModel(
            name='Precio',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='características',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inmuebles.características'),
        ),
    ]
